apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-ibm-cert-manager-operator
  namespace: "certNamespace"
  labels:
    component: cpfs3
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      name: "ibm-cert-manager-operator"
  policyTypes:
  - Egress