name: Open PR from the scripts-dev branch to the scripts-adopter branch

on:
  push:
    branches:
      - scripts-dev

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create PR
        run: |
          git checkout scripts-dev
          timestamp=$(date +%Y-%m-%d-%H-%M-%S)
          message="common service installer automation on $timestamp"
          base_branch="scripts-adopter"
          branch_to_merge="scripts-dev"
          # if a PR already exists, skip gh pr create
          result=$(gh pr list -B $base_branch -H $branch_to_merge)
          echo $result
          if [[ $result == *"No pull"* ]]; then
            echo "No PR found, creating a new one"
            gh pr create -B $base_branch -H $branch_to_merge --title 'Merge $branch_to_merge into $base_branch' --body '$message'
          else
            echo "PR already exists, skipping gh pr create"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
